spring:
  application:
    name:dine-in-order-api
  datasource:
    url: jdbc:mysql://localhost:3306/dine_in_db?createDatabaseIfNotExist=true
    username: root
    password: 7975
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update



